AWSTemplateFormatVersion: '2010-09-09'
Description: IoT Analytics Stack Example

Parameters:
  IoTTopicName:
    Type: String
    MinLength: 1
    Default: time-series-input
    Description: IoT Topic to send messages to.

Resources:
  #IoTTopicRuleAllEvents:
  #  Type: 'AWS::IoT::TopicRule'
  #  Properties:
  #    RuleName: send_to_iot_analytics
  #    TopicRulePayload:
  #      AwsIotSqlVersion: 2016-03-23
  #      RuleDisabled: 'false'
  #      Sql: !Sub |
  #        SELECT stac_passnumber,
  #            log_egc_currentactds,
  #            log_egc_speedfbds,
  #            unix_time,
  #            timestamp() AS recieved_on
  #        FROM '${IoTTopicName}'
  #      Actions:
  #        - IotAnalytics:
  #            ChannelName: !Ref IoTAnalyticsChannel
  #            RoleArn: !GetAtt IoTTopicRuleRole.Arn
  IoTAnalyticsChannel:
    Type: 'AWS::IoTAnalytics::Channel'
    Properties:
      ChannelName: iot_analytics_channel
      Tags:
        - Key: Project
          Value: !Ref AWS::StackName
  IoTAnalyticsPipeline:
    Type: 'AWS::IoTAnalytics::Pipeline'
    Properties:
      PipelineName: iot_analytics_pipeline
      PipelineActivities:
        - Channel:
            Name: ChannelActivity
            ChannelName: !Ref IoTAnalyticsChannel
            Next: SelectAttributesActivity
          SelectAttributes:
            Name: SelectAttributesActivity
            Attributes:
              - stac_passnumber
              - log_egc_currentactds
              - log_egc_speedfbds
              - unix_time
              - recieved_on
            Next: DatastoreActivity
          Datastore:
            Name: DatastoreActivity
            DatastoreName: !Ref IoTAnalyticsDatastore
      Tags:
        - Key: Project
          Value: !Ref AWS::StackName
  IoTAnalyticsDatastore:
    Type: 'AWS::IoTAnalytics::Datastore'
    Properties:
      DatastoreName: iot_analytics_data_store
      Tags:
        - Key: Project
          Value: !Ref AWS::StackName
  IoTAnalyticsDataset:
    Type: 'AWS::IoTAnalytics::Dataset'
    Properties:
      Actions:
        - ActionName: SqlAction
          QueryAction:
            SqlQuery: !Sub 'select * from ${IoTAnalyticsDatastore}'
      DatasetName: iot_analytics_data_set
      VersioningConfiguration:
        Unlimited: false
        MaxVersions: 2
      ContentDeliveryRules:
        - Destination:
            S3DestinationConfiguration:
              Bucket: !Ref DataSetOutputBucket
              RoleArn: !GetAtt DataSetOutputBucketRole.Arn
              Key: 'timeseries/!{iotanalytics:scheduleTime}/!{iotanalytics:versionId}.csv'
      Triggers:
        - Schedule:
            ScheduleExpression: cron(24 * * * ? *)
      Tags:
        - Key: Project
          Value: !Ref AWS::StackName
  DataSetOutputBucket:
    DeletionPolicy: Retain
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: !Ref AWS::StackName
  DataSetOutputBucketRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - iotanalytics.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: 'DataSetOutputBucketPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              Effect: Allow
              Action:
                - s3:PutObject
                - s3:DeleteObject
                - s3:GetBucketLocation
                - s3:GetObject
                - s3:ListBucket
                - s3:ListBucketMultipartUploads
                - s3:ListMultipartUploadParts
                - s3:AbortMultipartUpload
              Resource:
                - !Sub '${DataSetOutputBucket.Arn}'
                - !Sub '${DataSetOutputBucket.Arn}/*'
  IoTAnalyticsPipelineRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - iotanalytics.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: IoTTopicRulePolicyDeviceRegistry
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              Effect: Allow
              Action:
                - iot:DescribeThing
              Resource: !Join
                - ''
                - - 'arn:aws:iot:'
                  - !Ref 'AWS::Region'
                  - ':'
                  - !Ref 'AWS::AccountId'
                  - ':thing/'
                  - '*'
      Tags:
        - Key: Project
          Value: !Ref AWS::StackName
  IoTTopicRuleRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - iot.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: IoTTopicRulePolicyIoTAnalyticsChannel
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              Effect: Allow
              Action:
                - iotanalytics:BatchPutMessage
              Resource: !Join
                - ''
                - - 'arn:aws:iotanalytics:'
                  - !Ref 'AWS::Region'
                  - ':'
                  - !Ref 'AWS::AccountId'
                  - ':channel/'
                  - !Ref IoTAnalyticsChannel
      Tags:
        - Key: Project
          Value: !Ref AWS::StackName
  # IoTAnalyticsLoggingRole:
  #   Type: 'AWS::IAM::Role'
  #   Properties:
  #     AssumeRolePolicyDocument:
  #       Version: 2012-10-17
  #       Statement:
  #         - Effect: Allow
  #           Principal:
  #             Service:
  #               - iotanalytics.amazonaws.com
  #           Action:
  #             - 'sts:AssumeRole'
  #     Path: /
  #     Policies:
  #       - PolicyName: IoTAnalyticsLoggingPolicy
  #         PolicyDocument:
  #           Version: 2012-10-17
  #           Statement:
  #             Effect: Allow
  #             Action:
  #               - logs:CreateLogGroup
  #               - logs:CreateLogStream
  #             Resource: "*"
  #     Tags:
  #       - Key: Project
  #         Value: !Ref AWS::StackName
Outputs:
  IncomingIoTDataTopicName:
    Value: !Ref IoTTopicName
